### ISSUE TITLE
Create Progression flow for game levels

### ISSUE THREAD

**Issue by nweber28** [cwierzbicki00/gamma-physics#27]
Some sort of visual/documentation for different levels to the game and what objects are thrown on what level, etc.

**Comment by cwierzbicki00** [comment]
https://www.figma.com/file/phLx39C8Z4vxmuPjr4BKZ2/Flows-for-Throw-It-In!---Gamma-Physics-SWE-23?node-id=0%3A1&t=jWNANmYVYPscbhQL-1
