### ISSUE TITLE
Implement scoring and score tracking

### ISSUE THREAD

**Issue by rsmith531** [cwierzbicki00/gamma-physics#34]

**Comment by MohShahin** [comment]
let score =0;

if (ball.checkCollision(hoop)) {
    console.log("You scored!");
    score++;
  }
  textSize(24);
  fill(0, 0, 0);
  text("Score: " + score, 10, 30);

**Comment by rsmith531** [comment]
Added score tracking and updating to score-tracking branch. We need to think of when to change levels, when the player wins, how much to increment by (and if it changes based on difficulty).
