### ISSUE TITLE
Different maps with different gravity scales and wind directions

### ISSUE THREAD

**Issue by quoc796** [cwierzbicki00/gamma-physics#6]

**Comment by KoopaPig** [comment]
Before we do different maps, we should establish one test room where things like gravity and the weight of the object is editable.

**Comment by MohShahin** [comment]
update() {
    let friction = this.vel.copy();
    friction.mult(-1);
    friction.normalize();
    friction.mult(this.friction);
    this.applyForce(friction);

    this.vel.mult(this.airResistance);
    this.pos.add(this.vel);
  }
